export const Posts = [
    {
        id: 1,
        desc: "Love For All, Hatred For None.",
        photo: "https://images.pexels.com/photos/1075947/pexels-photo-1075947.jpeg?auto=compress&cs=tinysrgb&w=600",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
      },
      {
        id: 2,
        photo: "https://images.pexels.com/photos/3156482/pexels-photo-3156482.jpeg?auto=compress&cs=tinysrgb&w=600",
        date: "15 mins ago",
        userId: 2,
        like: 2,
        comment: 1,
      },
      {
        id: 3,
        desc: "Every moment is a fresh beginning.",
        photo: "https://images.pexels.com/photos/373543/pexels-photo-373543.jpeg?auto=compress&cs=tinysrgb&w=600",
        date: "1 hour ago",
        userId: 3,
        like: 61,
        comment: 2,
      },
      {
        id: 4,
        photo: "https://images.pexels.com/photos/933964/pexels-photo-933964.jpeg?auto=compress&cs=tinysrgb&w=600",
        date: "4 hours ago",
        userId: 4,
        like: 7,
        comment: 3,
      },
      {
        id: 5,
        photo: "https://images.pexels.com/photos/989941/pexels-photo-989941.jpeg?auto=compress&cs=tinysrgb&w=600",
        date: "5 hours ago",
        userId: 5,
        like: 23,
        comment: 5,
      },
      {
        id: 6,
        photo: "https://images.pexels.com/photos/2625664/pexels-photo-2625664.jpeg?auto=compress&cs=tinysrgb&w=600",
        date: "1 day ago",
        userId: 6,
        like: 44,
        comment: 6,
      },
      {
        id: 7,
        desc: "Flowerss... ",
        photo: "https://images.pexels.com/photos/1697912/pexels-photo-1697912.jpeg?auto=compress&cs=tinysrgb&w=600",
        date: "2 days ago",
        userId: 7,
        like: 52,
        comment: 3,
      },
      {
        id: 8,
        desc: "Mountains...",
        photo: "https://images.pexels.com/photos/9754/mountains-clouds-forest-fog.jpg?auto=compress&cs=tinysrgb&w=600",
        date: "3 days ago",
        userId: 8,
        like: 15,
        comment: 1,
      },
      {
        id: 9,
        desc: "Change the world by being yourself.",
        photo: "https://images.pexels.com/photos/933964/pexels-photo-933964.jpeg?auto=compress&cs=tinysrgb&w=600",
        date: "5 days ago",
        userId: 9,
        like: 11,
        comment: 2,
      },
      {
        id: 10,
        photo: "https://images.pexels.com/photos/3998365/pexels-photo-3998365.png?auto=compress&cs=tinysrgb&w=600",
        date: "1 week ago",
        userId: 10,
        like: 104,
        comment: 12,
      },

]

export const Users =[
    {
        id:1,
        name:"John Doe",
        profilePicture:"person/1.jpeg",
    },
    {
        id:2,
        name:"Jane Doe",
        profilePicture:"person/2.jpeg",
    },
    {
        id:3,
        name:"James Doe",
        profilePicture:"person/3.jpeg",
    },
    {
        id:4,
        name:"Jill Doe",
        profilePicture:"person/4.jpeg",
    },
    {
        id:5,
        name:"Jenny Doe",
        profilePicture:"person/5.jpeg",
    },
    {
        id:6,
        name:"Ratan Tata",
        profilePicture:"person/6.jpeg",
    },
    {
        id:7,
        name:"Gautam Adani",
        profilePicture:"person/7.jpeg",
    },
    {
        id:8,
        name:"Jeff Bezos",
        profilePicture:"person/8.jpeg",
    },
    {
        id:9,
        name:"Mukesh Ambani",
        profilePicture:"person/9.jpeg",
    },
    {
        id:10,
        name:"Steve Jobs",
        profilePicture:"person/10.jpeg",
    }
]